### ISSUE TITLE
线路模拟貌似不可用

### ISSUE THREAD

**Issue by QKMoco** [BobH233/FakeLocation-server#6]
线路模拟貌似是有些问题的，有时他总是定位在最初始的地方不再移动。希望您能更新修复它，谢谢你。

**Comment by BobH233** [comment]
抱歉，软件层面的代码我目前没有打算修复，这只是一个模拟服务端，不具有修改软件代码的能力

**Comment by Wkuny** [comment]
你如果想用这个搞什么闪动校园或是什么乐跑的话 那个定位就是不动的 或者根本定位不到你
